# Gitleaks configuration for terraform-provider-pbs
# https://github.com/gitleaks/gitleaks

title = "Gitleaks config for terraform-provider-pbs"

# Use the default gitleaks rules
[extend]
useDefault = true

# Allowlist patterns - these are safe to ignore
[allowlist]
description = "Allowlist for safe patterns"

# Files to ignore (documentation about secrets, not actual new secrets)
paths = [
    '''.gitleaks\.toml''',
]

# Content patterns to ignore (known safe values)
regexes = [
    '''pbspbs''',                  # Test password for Docker image (pre-configured)
    '''password123''',             # Test password used in Vagrant/VM provisioning
    '''os\.Getenv''',              # Code that reads env vars (not the values)
]

# Stop scanning at a specific commit (set after cleanup)
# commits = ["YOUR_CLEAN_COMMIT_HASH_HERE"]
